
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server.port: 8080
open:
  gateway:
    auth-base-url: http://localhost:5080
    use-redis: false
    component:
      app-id: wx4b4385cff773f3f9
      secret: ec8bcde9504c0ea1701988c5e741b865
      key: BojYAIsgTGPFqgtphrqR4j2Lmz1IamBcPJgWGHvwKqw
      token: huiantongxin123123

logging.level.cloud.weixin.open.gateway.*: DEBUG      
      
---
spring:
  profiles: prod
  redis:
    host: localhost
    port: 6379

server.port: 8002
open:
  gateway:
    auth-base-url: http://www.jilinjobswx.cn
    use-redis: true
    component:
      app-id: wx4b4385cff773f3f9
      secret: ec8bcde9504c0ea1701988c5e741b865
      key: BojYAIsgTGPFqgtphrqR4j2Lmz1IamBcPJgWGHvwKqw
      token: huiantongxin123123
      
